# Configuration file for analysis

# Data from Crits-Christoph et al report: https://zenodo.org/record/7754299#.ZCTNLezMKX0
crits_christoph_data:
  file_info: https://raw.githubusercontent.com/sars-cov-2-origins/huanan-environmental/bd2afdb19392a0efb872c09eb94045de9d265a6e/tables/TableS1_FileInformation.csv
  sample_names: https://raw.githubusercontent.com/sars-cov-2-origins/huanan-environmental/bd2afdb19392a0efb872c09eb94045de9d265a6e/tables/TableS2_SampleNames.csv
  read_counts: https://raw.githubusercontent.com/sars-cov-2-origins/huanan-environmental/bd2afdb19392a0efb872c09eb94045de9d265a6e/tables/TableS3_MappedReadCounts.csv

# get mitochondrial genome sets from here;
mitochondrial_genomes: https://ftp.ncbi.nlm.nih.gov/refseq/release/mitochondrion/mitochondrion.1.genomic.gbff.gz
extra_mitochondrial_genomes:  # extra genomes used by Crits-Christoph but not in RefSeq set
  - KX964606.1  # Erinaceus amurensis (Amur hedgehog)

# only keep mitochondrial genomes from listed phyla and subphyla
mitochondrial_taxa_to_keep:
  phylum: [Chordata]
  subphylum: []

# Always keep these mitochondrial genomes when do clustering to remove overly similar ones,
# and define common names (synonyms) for them. The list basically includes the ones in
# the Crits-Christoph et al (https://zenodo.org/record/7754299#.ZCTNLezMKX0) Table S3
# plus some other common ones in paper.
mitochondrial_genomes_to_keep:
  # all species listed in Table S3 of Crits Christoph et al
  # Crits-Christop Figure 1, https://zenodo.org/record/7754299#.ZCTNLezMKX0
  Amur hedgehog: Erinaceus amurensis
  pig: Sus scrofa domesticus
  brown rat: Rattus norvegicus strain Wistar
  rabbit: Oryctolagus cuniculus
  dog: Canis lupus familiaris
  European hedgehog: Erinaceus europaeus
  long-eared hedgehog: Hemiechinus auritus
  cow: Bos taurus
  human: Homo sapiens
  raccoon dog: Nyctereutes procyonoides
  Himalayan marmot: Marmota himalayana
  Siberian weasel: Mustela sibirica
  hog badger: Arctonyx collaris
  hoary bamboo rat: Rhizomys pruinosus
  fennec fox: Vulpes zerda
  sheep: Ovis orientalis
  gray fox: Urocyon cinereoargenteus
  goat: Capra aegagrus
  sand cat: Felis margarita
  masked palm civet: Paguma larvata
  Mayalan field rat: Rattus tiomanicus
  bat-eared fox: Otocyon megalotis
  leaf deer: Muntiacus putaoensis
  Malayan porcupine: Hystrix brachyura
  # some additional animals of interest that have hits in actual data
  quail: Coturnix japonica
  yellow croaker (fish): Larimichthys crocea
  spotted dove: Streptopelia chinensis
  swamp eel: Monopterus albus
  chicken: Gallus gallus spadiceus
  Oriental rat snake: Ptyas mucosa
  carp: Ctenopharyngodon idella
  snakehead fish: Channa maculata
  spot-billed duck: Anas poecilorhyncha
  catfish: Ictalurus punctatus
  Chinese salamander: Andrias davidianus
  brown bush hen: Amaurornis akool
  Chinese cobra: Naja atra
  Largemouth bass: Micropterus salmoides salmoides
  pigeon: Columba rupestris

# we only keep mitochondrial genomes that are either in the list to keep above,
# or have a mash distances >= this from all other retained ones.
# This identity of 0.93 (distance of 0.07) is same used by Crits-Christoph et al.
mitochondrial_genome_min_mash_dist: 0.07

# SARS-CoV-2 reference genome
sars2_ref: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/bigZips/wuhCor1.fa.gz
sars2_ref_id: NC_045512v2  # id of reference genome
sars2_ref_trim_3_polyA: true  # trim 3' polyA tail before using

# filter alignments to only retain reads with at least this mapping quality
min_mapq: 4

# flags passed to `coverm` when computing read counts and coverage. Reads
# are only counted if they meet these flags.
coverm_flags:
  min_read_aligned_length: 40
  contig_end_exclusion: 100
  min_read_percent_identity: 0.95

# Consider only these descriptions as representing metagenomic samples:
metagenomic_descriptions:
  - RNA sequencing of total nucleic acids from environmental swabs for metagenomics

# When calculating mitochondrial genome composition, apply the following filters:
mito_composition_filters:
  # only keep runs with  >= this many primary alignments across all mitochondrial genomes
  min_alignments_run_filter: 500
  # only keep mitochondrial genomes that have >= this percentage of all primary
  # aligned reads for at least one run
  min_percent_aligned_genome_filter: 20
  # only keep mitochondrial genomes that have >= this many covered bases for at least one one run
  min_coverage_aligned_genome_filter: 4000
