# Configuration file for analysis

# Data from Crits-Christoph et al report: https://zenodo.org/record/7754299#.ZCTNLezMKX0
crits_christoph_data:
  file_info: https://raw.githubusercontent.com/sars-cov-2-origins/huanan-environmental/bd2afdb19392a0efb872c09eb94045de9d265a6e/tables/TableS1_FileInformation.csv
  sample_names: https://raw.githubusercontent.com/sars-cov-2-origins/huanan-environmental/bd2afdb19392a0efb872c09eb94045de9d265a6e/tables/TableS2_SampleNames.csv
  read_counts: https://raw.githubusercontent.com/sars-cov-2-origins/huanan-environmental/bd2afdb19392a0efb872c09eb94045de9d265a6e/tables/TableS3_MappedReadCounts.csv

# get mitochondrial genome sets from here;
mitochondrial_genomes: https://ftp.ncbi.nlm.nih.gov/refseq/release/mitochondrion/mitochondrion.1.genomic.gbff.gz

# only keep mitochondrial genomes from listed phyla and subphyla
mitochondrial_taxa_to_keep:
  phylum: [Chordata]
  subphylum: []

# Always keep these mitochondrial genomes when do clustering to remove overly similar ones,
# and define common names (synonyms) for them. The list basically includes the ones in
# the Crits-Christoph et al (https://zenodo.org/record/7754299#.ZCTNLezMKX0) Table S3
# plus some other common ones in paper.
mitochondrial_genomes_to_keep:
  # all species listed in Table S3 of Crits Christoph et al
  # Crits-Christop Figure 1, https://zenodo.org/record/7754299#.ZCTNLezMKX0
  # Amur hedgehog: Erinaceus amurensis  # cannot find in RefSeq mitochondrial genomes
  pig: Sus scrofa domesticus
  brown rat: Rattus norvegicus strain Wistar
  rabbit: Oryctolagus cuniculus
  dog: Canis lupus familiaris
  European hedgehog: Erinaceus europaeus
  long-eared hedgehog: Hemiechinus auritus
  cow: Bos taurus
  human: Homo sapiens
  raccoon dog: Nyctereutes procyonoides
  Himalayan marmot: Marmota himalayana
  Siberian weasel: Mustela sibirica
  hog badger: Arctonyx collaris
  hoary bamboo rat: Rhizomys pruinosus
  fennec fox: Vulpes zerda
  sheep: Ovis orientalis
  gray fox: Urocyon cinereoargenteus
  goat: Capra aegagrus
  sand cat: Felis margarita
  masked palm civet: Paguma larvata
  Mayalan field rat: Rattus tiomanicus
  bat-eared fox: Otocyon megalotis
  leaf deer: Muntiacus putaoensis
  Malayan porcupine: Hystrix brachyura
  # some additional animals of interest
  cat: Felis catus
  chicken: Gallus gallus spadiceus
  duck: Anas poecilorhyncha
  crocodile: Osteolaemus tetraspis
  Japanese salamander: Andrias japonicus
  rat snake: Elaphe dione
  snakehead fish: Channa maculata
  brown bush hen: Amaurornis akool
  collared dove: Streptopelia decaocto
  golden pheasant: Chrysolophus pictus

# Genomes used in Crits-Christoph et al Table S3 **not** included here, because they
# don't seem to be present in current NCBI RefSeq set of full mitochondrial genomes
# despite being listed as obtained from there in Crits-Christoph et al.
mitochondrial_genomes_crits_christoph_missing:
  - Amur hedgehog: Erinaceus amurensis

# we only keep mitochondrial genomes that are either in the list to keep above,
# or have a mash distances >= this from all other retained ones.
mitochondrial_genome_min_mash_dist: 0.1

# SARS-CoV-2 reference genome
sars2_ref: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/bigZips/wuhCor1.fa.gz
sars2_ref_id: NC_045512v2  # id of reference genome

# When aggregating counts, consider only these descriptions as representing
# metagenomic samples:
metagenomic_descriptions:
  - RNA sequencing of total nucleic acids from environmental swabs for metagenomics

# When calculating mitochondrial genome composition, apply the following filters:
mito_composition_filters:
  # only keep runs with  >= this many primary alignments across all mitochondrial genomes
  min_alignments_run_filter: 2000
  # only keep mitochondrial genomes that have >= this percentage of all primary
  # aligned reads for at least one run
  min_percent_aligned_genome_filter: 10

